# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08a759e65339a8dcacada3818226c2bc88aba770ae473a4f8148aaf7e6ff25c4e2a07221a1b84dd166f0003b446e1fb88f43aff08b26c1219407602ed229307c

test:
  secret_key_base: 37b1ba7c719efaac3f91b7078aa9a85e912c2bd71a368f79fd22a2c4930f2695a3b1727b286788129a90efe0395d146440c261807661126836f97fbf9070b54c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
